// Seed data for Prisha Enterprises products
// Based on frontend data with additional products to reach 10 total

const products = [
  {
    id: 1,
    name: "Prisha Smart LED TV - 32 inch",
    screen_size: "32 inches (81 cm)",
    resolution: "HD Ready",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features"],
    price: 7500,
    image_url: "/images/tv-32.jpeg",
    stock_quantity: 50
  },
  {
    id: 2,
    name: "Prisha Smart LED TV - 32 inch Voice Remote 4K",
    screen_size: "32 inches (81 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features", "4K Video Quality", "Voice Remote"],
    price: 10500,
    image_url: "/images/tv-32-remote.jpeg",
    stock_quantity: 50
  },
  {
    id: 3,
    name: "Prisha Smart LED TV - 43 inch",
    screen_size: "43 inches (109 cm)",
    resolution: "Full HD",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 2,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features"],
    price: 12500,
    image_url: "/images/tv-43.jpeg",
    stock_quantity: 50
  },
  {
    id: 4,
    name: "Prisha Smart LED TV - 43 inch Voice Remote 4K",
    screen_size: "43 inches (109 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 2,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features", "4K Video Quality", "Voice Remote"],
    price: 15500,
    image_url: "/images/tv-43-remote.png",
    stock_quantity: 50
  },
  {
    id: 5,
    name: "Prisha Smart LED TV - 50 inch Voice Remote 4K",
    screen_size: "50 inches (127 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 2,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features", "4K Video Quality", "Voice Remote"],
    price: 21500,
    image_url: "/images/tv-50.png",
    stock_quantity: 50
  },
  {
    id: 6,
    name: "Prisha Smart LED TV - 65 inch WebOS Voice Remote 4K",
    screen_size: "65 inches (165 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "WebOS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["WebOS Software", "4K Video Quality", "Voice Remote", "Smart TV Features"],
    price: 45500,
    image_url: "/images/tv-65.png",
    stock_quantity: 50
  },
  // Additional products to reach 10
  {
    id: 7,
    name: "Prisha Smart LED TV - 40 inch HD Ready",
    screen_size: "40 inches (101 cm)",
    resolution: "HD Ready",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 2,
    usb_ports: 1,
    aux_port: true,
    lan_port: false,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features"],
    price: 9500,
    image_url: "/images/tv-40.jpeg",
    stock_quantity: 50
  },
  {
    id: 8,
    name: "Prisha Smart LED TV - 55 inch 4K Ultra HD",
    screen_size: "55 inches (139 cm)",
    resolution: "4K Ultra HD",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: true,
    smart_features: ["4K Ultra HD", "Bluetooth Audio", "Smart TV Features"],
    price: 28500,
    image_url: "/images/tv-55.png",
    stock_quantity: 50
  },
  {
    id: 9,
    name: "Prisha Smart LED TV - 55 inch Voice Remote 4K",
    screen_size: "55 inches (139 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: false,
    smart_features: ["Smart TV Features", "4K Video Quality", "Voice Remote"],
    price: 25500,
    image_url: "/images/tv-55-remote.png",
    stock_quantity: 50
  },
  {
    id: 10,
    name: "Prisha Smart LED TV - 65 inch Smart 4K",
    screen_size: "65 inches (165 cm)",
    resolution: "4K Video Quality",
    panel_type: "LED Panel",
    os: "Smart TV OS",
    ram: null,
    rom: null,
    audio: null,
    hdmi_ports: 3,
    usb_ports: 2,
    aux_port: true,
    lan_port: true,
    wifi: true,
    bluetooth: true,
    smart_features: ["4K Video Quality", "Bluetooth Audio", "Voice Control", "Smart TV Features"],
    price: 42500,
    image_url: "/images/tv-65-2.png",
    stock_quantity: 50
  }
];

module.exports = products;
